apiVersion: v1
kind: Service
metadata:
  name: data3-svc
  labels:
    app: api
spec:
  selector:
    app: data3-api
  type: NodePort #LoadBalancer
  ports:
    - port: 80
    - TargetPort: 3000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data3-deployment
  labels:
    app: api
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: data3-api
          image: nigelpoulton/pluralsight-docker-ci:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
