apiVersion: apps/v1
kind: Deployment
metadata:
  name: data3-deployment
  labels:
    app: api
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: data3-api
          image: 030361376246.dkr.ecr.ap-southeast-1.amazonaws.com/k8s-api:v1.2
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
