apiVersion: v1
kind: Service
metadata:
  name: data3-api-svc
  labels:
    app: data3-api
    type: api
spec:
  selector:
    app: data3-api
    type: api
  type: LoadBalancer
  ports:
    - nodePort: 31000
      port: 80
      targetPort: 3000
