apiVersion: v1
kind: Service
metadata:
  name: data3-svc
  labels:
    app: api
spec:
  selector:
    app: data3-api
  type: NodePort #LoadBalancer
  ports:
    - port: 80
    - TargetPort: 3000
      protocol: TCP
