name: k8s cluster with gitHub actions
on:
  push:
    branches:
      - master
jobs:
  deploy-api:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: bukhbayar/k8s-api@v1.2
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Build Docker Image
        run: |
          ls -ltr
          pwd