name: "k8s with GitHub Actions"
on:
  push:
    branches:
      - master
jobs:
  k8s:
    name: "Deployment with k8s"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: "Preparing Env"
        run: |
          echo " "
          echo " --------------------------- KOPS ------------------------------------- "
          echo " "
          curl -Lo kops https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
          chmod +x ./kops
          sudo mv ./kops /usr/local/bin/
          echo " "
          echo " --------------------------- KUBECTL ------------------------------------- "
          echo " "
          curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          echo " "
          echo " --------------------------- AWSCLI ------------------------------------- "
          echo " "
          sudo apt-get update
          sudo apt-get install python3-setuptools
          pip3 install wheel
          pip3 install awscli
      - name: "Setup SSH Keys"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.k8S_SECRET_PRIVATE_KEY }}"
          ls ~/.ssh/
      - name: "Building Cluster"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          find / -name *.pub
          echo " "
          echo " --------------------------- VARIABLES ----------------------------------- "
          echo " "
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export NAME=api.data3.xyz
          export KOPS_STATE_STORE=s3://api-data3-xyz-state-store
          echo " "
          echo " --------------------------- K8S CLUSTER --------------------------------- "
          echo " "
          kops create secret --name api.data3.xyz sshpublickey admin -i ~/.ssh/id_rsa.pub
          kops create cluster \
            --name api.data3.xyz \
            --master-size t2.micro \
            --node-size t2.micro \
            --state s3://api-data3-xyz-state-store \
            --zones ap-southeast-1a
            --yes
