name: k8s cluster with gitHub actions
on:
  push:
    branches:
      - master
jobs:
  deploy-api:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH Keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.g_SECRET_PUBLIC_KEY }}" > ~/.ssh/github.pub
          echo "${{ secrets.g_SECRET_PRIVATE_KEY }}" > ~/.ssh/github
          echo "${{ secrets.g_CONFIG }}" > ~/.ssh/config
          ls -a -ltr ~/.ssh
          chmod 644 ~/.ssh/github.pub
          chmod 600 ~/.ssh/github
          chmod 644 ~/.ssh/config
      - name: Clone repo
        run: |
          git clone git@github.com:bukhbayar/k8s-api.git
      - name: Build Docker Image
        run: |
          ls -ltr
          pwd