name: k8s cluster with gitHub actions
on:
  push:
    branches:
      - master
jobs:
  deploy-api:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup
      - uses: actions/checkout@v2
      - name: Build Docker Image
      - uses: actions/checkout@v2
        with:
          repository: bukhbayar/k8s-api@v1.2
          token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker images