name: k8s cluster with gitHub actions
on:
  push:
    branches:
      - master
jobs:
  deploy-api:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          docker images