name: k8s cluster with gitHub actions
on:
  push:
    branches:
      - master
jobs:
  deploy-api:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH Keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.g_SECRET_PUBLIC_KEY }}" > ~/.ssh/github.pub
          echo "${{ secrets.g_SECRET_PRIVATE_KEY }}" > ~/.ssh/github
          echo "${{ secrets.g_CONFIG }}" > ~/.ssh/config
          chmod 644 ~/.ssh/github.pub
          chmod 600 ~/.ssh/github
          chmod 644 ~/.ssh/config
      - name: Clone repo
        run: |
          git clone git@github.com:bukhbayar/k8s-api.git
      - name: Build Docker Image
        run: |
          docker build -t k8s-api:v1.2 -f docker-api/Dockerfile .
      - name: Setup awscli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          mkdir -p ~/.aws
          echo "[default]
          aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region = ${{ secrets.AWS_REGION }}" > ~/.aws/credentials
      - name: AWS ECR Login
        run: |
          aws ecr get-login-password \
            --region ap-southeast-1 \
            | docker login \
            --username AWS \
            --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com
      - name: Setup ECR Repo
        run: |
          export REPO_NAME=$(aws ecr describe-repositories | jq -r '.repositories[].repositoryName' | grep 'k8s-api')
          if [ "$REPO_NAME" != "k8s-api" ]; then
            aws ecr create-repository \
              --repository-name k8s-api \
              --image-scanning-configuration scanOnPush=true \
              --region ap-southeast-1 \
              --tags Key=app, Value=api
          else
            echo "ECR Repo has been created!"
          fi
