name: "k8s with GitHub Actions"
on:
  push:
    branches:
      - master
jobs:
  k8s:
    name: "Install"
    runs-on: ubuntu-latest
    steps:
      - name: "kops"
        run: |
          curl -Lo kops https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
          chmod +x ./kops
          sudo mv ./kops /usr/local/bin/
          kops --version
          curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          pip --version
          pip install awscli
